const cfg = window.STAFF_APP_CONFIG || {};
const online = Boolean(window.supabase && cfg.SUPABASE_URL && cfg.SUPABASE_ANON_KEY && !String(cfg.SUPABASE_URL).includes('YOUR_') && !String(cfg.SUPABASE_ANON_KEY).includes('YOUR_'));
const supabaseClient = online ? window.supabase.createClient(cfg.SUPABASE_URL, cfg.SUPABASE_ANON_KEY, { auth: { autoRefreshToken: true, persistSession: true, detectSessionInUrl: true, flowType: 'implicit' } }) : null;
const demoAssignments = [
  { project_id: 'PILOT_TEST', shop_id: 'SHOP_A1', cskh_user_id: 'pilot-a', cskh_name: 'Nguyễn A', cbld_name: 'CBLĐ Pilot' },
  { project_id: 'PILOT_TEST', shop_id: 'SHOP_A2', cskh_user_id: 'pilot-a', cskh_name: 'Nguyễn A', cbld_name: 'CBLĐ Pilot' },
  { project_id: 'PILOT_TEST', shop_id: 'SHOP_B1', cskh_user_id: 'pilot-b', cskh_name: 'Nguyễn B', cbld_name: 'CBLĐ Pilot' }
];
const demoDebt = { SHOP_A1: { ps_kpi: 50000000, ps_collected: 10000000 }, SHOP_A2: { ps_kpi: 80000000, ps_collected: 60000000 }, SHOP_B1: { ps_kpi: 90000000, ps_collected: 20000000 } };
let assignments = [], shops = [], staffOptions = [], selectedStaffId = '', current = null, currentEvents = [], filter = 'all', currentUser = null, currentProfile = null;
const fmt = value => new Intl.NumberFormat('vi-VN').format(Number(value) || 0) + ' ₫';
const localDate = () => new Date().toISOString().slice(0, 10);
const eventKey = shop => `staffv1:${shop.project_id}:${shop.shop_id}`;
const localState = shop => JSON.parse(localStorage.getItem(eventKey(shop)) || '{"events":[]}');
const localSave = (shop, state) => localStorage.setItem(eventKey(shop), JSON.stringify(state));
const latestOf = (events, types) => [...events].reverse().find(e => types.includes(e.event_type || e.type));
const esc = value => String(value ?? '').replace(/[&<>"']/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch]));
function setMessage(text, isError = false) { for (const id of ['message', 'loginMessage', 'bootMessage']) { const node = document.getElementById(id); if (node) { node.textContent = text; node.className = isError ? 'message error' : 'message'; } } }
function normalizeShop(row) { return { ...row, project_id: row.project_id || cfg.PROJECT_ID || 'PILOT_TEST', shop_id: row.shop_id || row.shop, owner_staff_id: row.owner_staff_id || '', cskh_user_id: row.cskh_user_id || '', cskh_name: row.cskh_name || row.cskh || '', cbld_name: row.cbld_name || row.cbld || '', ps_kpi: Number(row.ps_kpi ?? row.ps ?? 0), ps_collected: Number(row.ps_collected ?? row.col ?? 0), official_kpi: Number(row.official_kpi ?? row.ps_kpi ?? row.ps ?? 0), official_collected: Number(row.official_collected ?? row.ps_collected ?? row.col ?? 0), __events: row.__events || [] }; }
function ownerKey(row) { return row.owner_staff_id || row.cskh_user_id || `name:${row.cskh_name}`; }
function buildStaffOptions() { const map = new Map(); assignments.forEach(a => { const key = ownerKey(a); if (!map.has(key)) map.set(key, { id: key, name: a.cskh_name || key, shopCount: 0 }); map.get(key).shopCount += 1; }); staffOptions = [...map.values()].sort((a, b) => a.name.localeCompare(b.name, 'vi')); if (!staffOptions.some(s => s.id === selectedStaffId)) selectedStaffId = localStorage.getItem('staffv1:last_selected_staff') || staffOptions[0]?.id || ''; }
async function loadOnlineData() { const [{ data: a, error: ae }, { data: d, error: de }, { data: e, error: ee }] = await Promise.all([supabaseClient.from('assignments').select('project_id,shop_id,owner_staff_id,cskh_user_id,cbld_user_id,cskh_name,cbld_name'), supabaseClient.from('shop_debt_snapshot').select('project_id,shop_id,as_of,ps_kpi,ps_collected,official_kpi,official_collected').order('as_of', { ascending: false }), supabaseClient.from('staff_events').select('project_id,shop_id,event_type,event_time,amount,expected_date,note').order('event_time', { ascending: true })]); if (ae || de || ee) throw ae || de || ee; assignments = a || []; const latest = new Map(); (d || []).forEach(row => { const key = `${row.project_id}::${row.shop_id}`; if (!latest.has(key)) latest.set(key, row); }); const events = new Map(); (e || []).forEach(row => { const key = `${row.project_id}::${row.shop_id}`; if (!events.has(key)) events.set(key, []); events.get(key).push(row); }); shops = assignments.map(row => normalizeShop({ ...row, ...(latest.get(`${row.project_id}::${row.shop_id}`) || {}), __events: events.get(`${row.project_id}::${row.shop_id}`) || [] })); buildStaffOptions(); }
function loadOfflineData() { assignments = demoAssignments; shops = assignments.map(a => normalizeShop({ ...a, ...(demoDebt[a.shop_id] || {}) })); buildStaffOptions(); }
async function loadProfile(user) { if (!online) return { user_id: user?.id || 'demo', email: user?.email || 'demo', role: 'SHARED_STAFF', display_name: 'Nhân viên dùng chung', active: true }; if (user?.is_anonymous) { const { data, error } = await supabaseClient.rpc('ensure_workspace_session'); if (error) throw error; return { ...(data || {}), user_id: user.id, role: 'SHARED_STAFF', display_name: 'Nhân viên dùng chung', active: true }; } const { data, error } = await supabaseClient.from('profiles').select('user_id,email,role,display_name,active').eq('user_id', user.id).maybeSingle(); if (error) throw error; if (!data || data.active === false) throw new Error('AUTH_PROFILE_REQUIRED'); return data; }
function renderAccount() { const node = document.getElementById('account'); if (!node || !currentProfile) return; node.innerHTML = `<b>${esc(currentProfile.display_name || currentProfile.email || 'Staff')}</b><span>${esc(currentProfile.role || '')} · ${esc(currentProfile.email || '')}</span>`; const adminButton = document.getElementById('adminAccessButton'); if (adminButton) adminButton.hidden = currentProfile.role !== 'ADMIN'; }
async function enterApp(user) { try { currentProfile = await loadProfile(user); currentUser = user; document.getElementById('login').hidden = true; document.getElementById('bootMessage').hidden = true; document.getElementById('app').hidden = false; renderAccount(); if (online) await loadOnlineData(); else loadOfflineData(); setMessage(online ? 'Đã kết nối Shared Staff Workspace. Công nợ chỉ đọc.' : 'Bản Candidate offline: dữ liệu demo lưu trên thiết bị.'); renderWorkspace(); } catch (error) { currentUser = null; currentProfile = null; if (online) await supabaseClient.auth.signOut({ scope: 'local' }).catch(() => {}); document.getElementById('login').hidden = true; document.getElementById('app').hidden = true; document.getElementById('bootMessage').hidden = false; setMessage(`Không khởi tạo được phiên dùng chung: ${error.message || error}`, true); } }
function shopEvents(shop) { return online ? (shop.__events || []) : (localState(shop).events || []); }
function currentPlan(events) { const plan = latestOf(events, ['PLAN_CHANGED', 'PLAN_CREATED']); const cancelled = latestOf(events, ['PLAN_CANCELLED']); return plan && (!cancelled || new Date(cancelled.event_time || cancelled.at) < new Date(plan.event_time || plan.at)) ? plan : null; }
function matchesFilter(shop) { const debt = Math.max(0, shop.ps_kpi - shop.ps_collected); const events = shopEvents(shop); const plan = currentPlan(events); const signal = latestOf(events, ['PAYMENT_REPORTED']); const date = plan?.expected_date || plan?.date || ''; if (filter === 'debt') return debt > 0; if (filter === 'noplan') return !plan; if (filter === 'today') return date === localDate(); if (filter === 'overdue') return Boolean(date && date < localDate()); if (filter === 'signal') return Boolean(signal); return true; }
function selectedShops() { const q = (document.getElementById('shopSearch')?.value || '').toLowerCase(); return shops.filter(s => ownerKey(s) === selectedStaffId && s.shop_id.toLowerCase().includes(q) && matchesFilter(s)); }
function renderWorkspace() { const staffSelect = document.getElementById('staffSelect'); if (staffSelect) { staffSelect.innerHTML = staffOptions.map(s => `<option value="${esc(s.id)}">${esc(s.name)} (${s.shopCount} Shop)</option>`).join(''); staffSelect.value = selectedStaffId; } const list = document.getElementById('list'); if (!list) return; const visible = selectedShops(); const debtTotal = visible.reduce((sum, s) => sum + Math.max(0, s.ps_kpi - s.ps_collected), 0); const noPlan = visible.filter(s => !currentPlan(shopEvents(s))).length; const signalCount = visible.filter(s => latestOf(shopEvents(s), ['PAYMENT_REPORTED'])).length; const overdue = visible.filter(s => { const p = currentPlan(shopEvents(s)); const d = p?.expected_date || p?.date; return d && d < localDate(); }).length; document.getElementById('workspaceSummary').textContent = `${visible.length} Shop · Còn phải thu ${fmt(debtTotal)} · Chưa kế hoạch ${noPlan} · Có tín hiệu ${signalCount} · Quá hạn ${overdue}`; const shopSelect = document.getElementById('shopSelect'); if (shopSelect) shopSelect.innerHTML = '<option value="">Chọn Shop</option>' + visible.map(s => `<option value="${esc(s.shop_id)}">${esc(s.shop_id)} — ${esc(s.cskh_name)}</option>`).join(''); list.innerHTML = ''; visible.forEach(shop => { const events = shopEvents(shop); const plan = currentPlan(events); const signal = latestOf(events, ['PAYMENT_REPORTED']); const debt = Math.max(0, shop.ps_kpi - shop.ps_collected); const card = document.createElement('div'); card.className = 'card'; card.innerHTML = `<b>${esc(shop.shop_id)}</b><div class="muted">Owner: ${esc(shop.cskh_name)} · ${esc(shop.cbld_name)}</div><p>Còn phải thu: <b>${fmt(debt)}</b></p><span class="badge">${plan ? 'Có kế hoạch' : 'Chưa có kế hoạch'}</span>${signal ? '<span class="badge">Có tín hiệu</span>' : ''}<button type="button">Mở Shop</button>`; card.querySelector('button').addEventListener('click', () => openShop(shop.shop_id)); list.appendChild(card); }); }
async function openShop(id) { current = shops.find(s => s.shop_id === id && ownerKey(s) === selectedStaffId); if (!current) return; try { currentEvents = await eventsFor(current); } catch (error) { return setMessage(`Không đọc được lịch sử: ${error.message}`, true); } const plan = currentPlan(currentEvents); document.getElementById('title').textContent = current.shop_id; document.getElementById('debt').innerHTML = `Shop: <b>${esc(current.shop_id)}</b><br>CSKH phụ trách: <b>${esc(current.cskh_name)}</b><br>CBLĐ: <b>${esc(current.cbld_name)}</b><br>Nợ PS: <b>${fmt(current.ps_kpi)}</b><br>Đã thu PS: <b>${fmt(current.ps_collected)}</b><br>Còn phải thu: <b>${fmt(current.ps_kpi - current.ps_collected)}</b>`; document.getElementById('pa').value = plan?.amount || ''; document.getElementById('pd').value = plan?.expected_date || plan?.date || ''; document.getElementById('pn').value = plan?.note || ''; history(); document.getElementById('shop').showModal(); }
async function eventsFor(shop) { if (!online) return localState(shop).events || []; const { data, error } = await supabaseClient.from('staff_events').select('*').eq('project_id', shop.project_id).eq('shop_id', shop.shop_id).order('event_time', { ascending: true }); if (error) throw error; return data || []; }
async function appendEvent(payload, previous = null) { if (!online) { const state = localState(current); state.events.push({ ...payload, owner_staff_id: current.owner_staff_id, type: payload.event_type, id: crypto.randomUUID(), at: new Date().toISOString(), by: currentProfile?.email || 'demo', before: previous || null }); localSave(current, state); currentEvents = state.events; return state.events[state.events.length - 1]; } const { data, error } = await supabaseClient.rpc('workspace_append_event', { p_project_id: current.project_id, p_shop_id: current.shop_id, p_event_type: payload.event_type, p_amount: payload.amount ?? null, p_expected_date: payload.expected_date ?? null, p_signal_type: payload.signal_type ?? null, p_note: payload.note ?? null, p_supersedes_event_id: payload.supersedes_event_id ?? null, p_cancelled_reason: payload.cancelled_reason ?? null, p_payload: payload.payload || {} }); if (error) throw error; const row = Array.isArray(data) ? data[0] : data; if (!row) throw new Error('EVENT_NOT_CREATED'); currentEvents.push(row); return row; }
async function plan() { const amount = Number(document.getElementById('pa').value) || 0; const date = document.getElementById('pd').value; if (!amount || !date) return setMessage('Nhập đủ số tiền và ngày dự kiến thu.', true); const old = currentPlan(currentEvents); try { await appendEvent({ event_type: old ? 'PLAN_CHANGED' : 'PLAN_CREATED', amount, expected_date: date, note: document.getElementById('pn').value, supersedes_event_id: old?.event_id || null }, old); setMessage('Đã lưu kế hoạch theo nhân viên phụ trách; lịch sử cũ vẫn được giữ.'); history(); refreshCurrentShop(); } catch (error) { setMessage(`Không lưu được kế hoạch: ${error.message}`, true); } }
async function cancelPlan() { const old = currentPlan(currentEvents); if (!old) return setMessage('Shop chưa có kế hoạch hiện tại.', true); const reason = document.getElementById('pn').value.trim() || 'Người dùng yêu cầu hủy'; try { await appendEvent({ event_type: 'PLAN_CANCELLED', cancelled_reason: reason, supersedes_event_id: old.event_id || null }, old); setMessage('Đã ghi event hủy; không xóa lịch sử.'); history(); refreshCurrentShop(); } catch (error) { setMessage(`Không hủy được kế hoạch: ${error.message}`, true); } }
async function signal() { const amount = Number(document.getElementById('sa').value) || 0; const date = document.getElementById('sd').value; if (!amount || !date) return setMessage('Nhập đủ số tiền và ngày khách báo thanh toán.', true); const file = document.getElementById('unc').files[0]; if (file && (file.size > 10 * 1024 * 1024 || !['application/pdf','image/jpeg','image/png'].includes(file.type))) return setMessage('UNC phải là PDF/JPG/PNG và không quá 10 MB.', true); try { const event = await appendEvent({ event_type: 'PAYMENT_REPORTED', signal_type: document.getElementById('st').value, amount, expected_date: date, note: document.getElementById('sn').value, payload: {} }); if (online && file && event?.event_id) { const safeName = file.name.replace(/[^a-zA-Z0-9._-]/g, '_'); const path = `${current.project_id}/${current.shop_id}/${event.event_id}/${safeName}`; const { error: uploadError } = await supabaseClient.storage.from(cfg.EVIDENCE_BUCKET || 'unc').upload(path, file, { upsert: false, contentType: file.type }); if (uploadError) throw uploadError; const { error: metadataError } = await supabaseClient.rpc('workspace_register_evidence', { p_payment_event_id: event.event_id, p_project_id: current.project_id, p_shop_id: current.shop_id, p_storage_path: path, p_original_filename: file.name, p_mime_type: file.type, p_size_bytes: file.size }); if (metadataError) throw metadataError; await appendEvent({ event_type: 'EVIDENCE_UPLOADED', note: file.name, payload: { payment_event_id: event.event_id, storage_path: path } }); } setMessage('Đã lưu Tín hiệu thanh toán. Đây không phải tiền SAP đã thu.'); history(); refreshCurrentShop(); } catch (error) { setMessage(`Không lưu được Tín hiệu/UNC: ${error.message}`, true); } }
function refreshCurrentShop() { if (current) { const idx = shops.findIndex(s => s.shop_id === current.shop_id && s.project_id === current.project_id); if (idx >= 0 && !online) current.__events = currentEvents; } renderWorkspace(); }
function history() { const node = document.getElementById('hist'); const events = [...currentEvents].reverse(); node.innerHTML = events.length ? events.map(event => `<div class="event"><b>${esc(event.event_type || event.type)}</b> · ${esc(new Date(event.event_time || event.at).toLocaleString('vi-VN'))}<br>${event.amount != null ? fmt(event.amount) : ''} ${esc(event.expected_date || event.date || '')} ${esc(event.signal_type || '')}<div class="muted">${esc(event.note || event.cancelled_reason || '')}</div></div>`).join('') : '<span class="muted">Chưa có lịch sử.</span>'; }
async function logout() { if (online) await supabaseClient.auth.signOut({ scope: 'local' }); currentUser = null; currentProfile = null; shops = []; document.getElementById('app').hidden = true; document.getElementById('login').hidden = false; setMessage('Đã đăng xuất.'); }
async function loadAdminAccessList() { if (!online || currentProfile?.role !== 'ADMIN') return; const [{ data: profiles, error: pe }, { data: a, error: ae }] = await Promise.all([supabaseClient.from('profiles').select('user_id,email,role,display_name,active'), supabaseClient.from('assignments').select('cskh_user_id,cbld_user_id')]); if (pe || ae) throw pe || ae; const counts = {}; (a || []).forEach(row => [row.cskh_user_id, row.cbld_user_id].filter(Boolean).forEach(id => { counts[id] = (counts[id] || 0) + 1; })); document.getElementById('adminList').innerHTML = (profiles || []).map(p => `<tr><td>${esc(p.display_name || '')}</td><td>${esc(p.role)}</td><td>${esc(p.email)}</td><td>${counts[p.user_id] || 0}</td><td>${p.active ? 'Đang hoạt động' : 'Tạm khóa'}</td></tr>`).join('') || '<tr><td colspan="5">Chưa có nhân sự Pilot.</td></tr>'; document.getElementById('adminDialog').showModal(); }
async function go() { const email = document.getElementById('email').value.trim(); if (!email) return setMessage('Nhập email công việc để nhận mã/link đăng nhập.', true); if (!online) return enterApp(); const redirect = `${window.location.origin}${window.location.pathname}`; const { error } = await supabaseClient.auth.signInWithOtp({ email, options: { emailRedirectTo: redirect } }); if (error) return setMessage(`Không gửi được mã/link đăng nhập: ${error.message}`, true); setMessage('Đã gửi mã/link đăng nhập. Mở email mới nhất rồi quay lại App.'); }
function init() { document.getElementById('q')?.addEventListener('input', renderWorkspace); document.getElementById('shopSearch')?.addEventListener('input', renderWorkspace); document.getElementById('staffSelect')?.addEventListener('change', event => { selectedStaffId = event.target.value; localStorage.setItem('staffv1:last_selected_staff', selectedStaffId); renderWorkspace(); }); document.getElementById('shopSelect')?.addEventListener('change', event => { if (event.target.value) openShop(event.target.value); }); document.querySelectorAll('[data-filter]').forEach(button => button.addEventListener('click', () => { filter = button.dataset.filter; renderWorkspace(); })); if (!online) return enterApp(); (async () => { const { data: existing, error: sessionError } = await supabaseClient.auth.getSession(); if (sessionError) return setMessage(`Không đọc được phiên dùng chung: ${sessionError.message}`, true); if (existing.session) return enterApp(existing.session.user); const { error: signInError } = await supabaseClient.auth.signInAnonymously(); if (signInError) return setMessage(`Không khởi tạo được phiên dùng chung: ${signInError.message}`, true); const { data: currentSession, error: currentSessionError } = await supabaseClient.auth.getSession(); if (currentSessionError || !currentSession.session) return setMessage('ANONYMOUS_SESSION_NOT_READY', true); await enterApp(currentSession.session.user); })(); }
window.go = go; window.plan = plan; window.cancelPlan = cancelPlan; window.signal = signal; window.logout = logout; window.loadAdminAccessList = loadAdminAccessList; window.closeShop = () => document.getElementById('shop').close(); window.closeInfo = () => document.getElementById('info').close(); window.closeAdmin = () => document.getElementById('adminDialog').close(); window.addEventListener('DOMContentLoaded', init);

