const cfg = window.STAFF_APP_CONFIG || {};
const online = Boolean(window.supabase && cfg.SUPABASE_URL && cfg.SUPABASE_ANON_KEY && !String(cfg.SUPABASE_URL).includes('YOUR_') && !String(cfg.SUPABASE_ANON_KEY).includes('YOUR_'));
const supabaseClient = online ? window.supabase.createClient(cfg.SUPABASE_URL, cfg.SUPABASE_ANON_KEY) : null;
const demoShops = [
  { project_id: 'OCEAN_CITY', shop_id: 'TP.TV-42', cskh_name: 'Nguyễn A', cbld_name: 'CBLĐ Demo', ps_kpi: 120000000, ps_collected: 60000000 },
  { project_id: 'OCEAN_CITY', shop_id: 'HA.01-15', cskh_name: 'Nguyễn A', cbld_name: 'CBLĐ Demo', ps_kpi: 85000000, ps_collected: 70000000 },
  { project_id: 'OCEAN_CITY', shop_id: 'SF.02-08', cskh_name: 'Nguyễn A', cbld_name: 'CBLĐ Demo', ps_kpi: 150000000, ps_collected: 90000000 }
];
let shops = [];
let current = null;
let currentEvents = [];
let filter = 'all';
let currentUser = null;
const fmt = value => new Intl.NumberFormat('vi-VN').format(Number(value) || 0) + ' ₫';
const eventKey = shop => `staffv1:${shop.project_id}:${shop.shop_id}`;
const localState = shop => JSON.parse(localStorage.getItem(eventKey(shop)) || '{"events":[]}');
const localSave = (shop, state) => localStorage.setItem(eventKey(shop), JSON.stringify(state));
const latestOf = (events, types) => [...events].reverse().find(e => types.includes(e.event_type || e.type));
const esc = value => String(value ?? '').replace(/[&<>"']/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch]));
function setMessage(text, isError = false) { const node = document.getElementById('message'); if (node) { node.textContent = text; node.className = isError ? 'message error' : 'message'; } }
function normalizeShop(row) { return { project_id: row.project_id || row.project || cfg.PROJECT_ID || 'OCEAN_CITY', shop_id: row.shop_id || row.shop, cskh_name: row.cskh_name || row.cskh || '', cbld_name: row.cbld_name || row.cbld || '', ps_kpi: Number(row.ps_kpi ?? row.ps ?? 0), ps_collected: Number(row.ps_collected ?? row.col ?? 0), official_kpi: Number(row.official_kpi ?? row.ps_kpi ?? row.ps ?? 0), official_collected: Number(row.official_collected ?? row.ps_collected ?? row.col ?? 0) }; }
async function loadOnlineShops() {
  const { data: assignments, error: assignmentError } = await supabaseClient.from('assignments').select('project_id,shop_id,cskh_name,cbld_name');
  if (assignmentError) throw assignmentError;
  const { data: debtRows, error: debtError } = await supabaseClient.from('shop_debt_snapshot').select('project_id,shop_id,as_of,ps_kpi,ps_collected,official_kpi,official_collected').order('as_of', { ascending: false });
  if (debtError) throw debtError;
  const latest = new Map();
  (debtRows || []).forEach(row => { const key = `${row.project_id}::${row.shop_id}`; if (!latest.has(key)) latest.set(key, row); });
  shops = (assignments || []).map(row => normalizeShop({ ...row, ...(latest.get(`${row.project_id}::${row.shop_id}`) || {}) }));
}
async function enterApp() { document.getElementById('login').hidden = true; document.getElementById('app').hidden = false; setMessage(online ? 'Đã kết nối Pilot Supabase. Dữ liệu công nợ chỉ đọc.' : 'Bản Candidate offline: dữ liệu demo lưu trên thiết bị.'); if (online) { try { await loadOnlineShops(); } catch (error) { setMessage(`Không đọc được dữ liệu Pilot: ${error.message}`, true); shops = []; } } else shops = demoShops.map(normalizeShop); render(); }
async function go() { const email = document.getElementById('email').value.trim(); if (!email) return setMessage('Nhập email công việc để nhận liên kết đăng nhập.', true); if (!online) return enterApp(); const redirect = `${window.location.origin}${window.location.pathname}`; const { error } = await supabaseClient.auth.signInWithOtp({ email, options: { emailRedirectTo: redirect } }); if (error) return setMessage(`Không gửi được liên kết đăng nhập: ${error.message}`, true); setMessage('Đã gửi liên kết đăng nhập. Kiểm tra email công việc rồi mở liên kết trong cùng trình duyệt.'); }
async function eventsFor(shop) { if (!online) return localState(shop).events || []; const { data, error } = await supabaseClient.from('staff_events').select('*').eq('project_id', shop.project_id).eq('shop_id', shop.shop_id).order('event_time', { ascending: true }); if (error) throw error; return data || []; }
function currentPlan(events) { const plan = latestOf(events, ['PLAN_CHANGED', 'PLAN_CREATED']); const cancelled = latestOf(events, ['PLAN_CANCELLED']); return plan && (!cancelled || new Date(cancelled.event_time || cancelled.at) < new Date(plan.event_time || plan.at)) ? plan : null; }
function render() { const list = document.getElementById('list'); const query = (document.getElementById('q').value || '').toLowerCase(); list.innerHTML = ''; shops.filter(shop => shop.shop_id.toLowerCase().includes(query)).forEach(shop => { const events = online ? (shop.__events || []) : (localState(shop).events || []); const plan = currentPlan(events); const signal = latestOf(events, ['PAYMENT_REPORTED']); if (filter === 'noplan' && plan) return; if (filter === 'signal' && !signal) return; const card = document.createElement('div'); card.className = 'card'; card.innerHTML = `<b>${esc(shop.shop_id)}</b><div class="muted">${esc(shop.cskh_name)}</div><p>Nợ PS còn phải thu: <b>${fmt(Math.max(0, shop.ps_kpi - shop.ps_collected))}</b></p><span class="badge">${plan ? 'Có kế hoạch' : 'Chưa có kế hoạch'}</span>${signal ? '<span class="badge">Có tín hiệu</span>' : ''}<button type="button">Mở Shop</button>`; card.querySelector('button').addEventListener('click', () => openShop(shop.shop_id)); list.appendChild(card); }); }
async function openShop(id) { current = shops.find(shop => shop.shop_id === id); if (!current) return; try { currentEvents = await eventsFor(current); } catch (error) { return setMessage(`Không đọc được lịch sử: ${error.message}`, true); } const plan = currentPlan(currentEvents); document.getElementById('title').textContent = current.shop_id; document.getElementById('debt').innerHTML = `Nợ PS: <b>${fmt(current.ps_kpi)}</b><br>Đã thu PS: <b>${fmt(current.ps_collected)}</b><br>Còn phải thu: <b>${fmt(current.ps_kpi - current.ps_collected)}</b>`; document.getElementById('pa').value = plan?.amount || ''; document.getElementById('pd').value = plan?.expected_date || plan?.date || ''; document.getElementById('pn').value = plan?.note || ''; history(); document.getElementById('shop').showModal(); }
async function appendEvent(payload, previous = null) { if (!online) { const state = localState(current); state.events.push({ ...payload, type: payload.event_type, id: crypto.randomUUID(), at: new Date().toISOString(), by: document.getElementById('email').value || 'demo', before: previous || null }); localSave(current, state); currentEvents = state.events; return; } const row = { ...payload, project_id: current.project_id, shop_id: current.shop_id, created_by: currentUser.id }; const { data, error } = await supabaseClient.from('staff_events').insert(row).select().single(); if (error) throw error; currentEvents.push(data); }
async function plan() { const amount = Number(document.getElementById('pa').value) || 0; const expectedDate = document.getElementById('pd').value; if (!amount || !expectedDate) return setMessage('Nhập đủ số tiền và ngày dự kiến thu.', true); const old = currentPlan(currentEvents); try { await appendEvent({ event_type: old ? 'PLAN_CHANGED' : 'PLAN_CREATED', amount, expected_date: expectedDate, note: document.getElementById('pn').value, supersedes_event_id: old?.event_id || null }, old); setMessage('Đã lưu kế hoạch bằng event mới; lịch sử cũ vẫn được giữ.'); history(); render(); } catch (error) { setMessage(`Không lưu được kế hoạch: ${error.message}`, true); } }
async function cancelPlan() { const old = currentPlan(currentEvents); if (!old) return setMessage('Shop chưa có kế hoạch hiện tại.', true); const reason = window.prompt('Lý do hủy kế hoạch?'); if (!reason) return; try { await appendEvent({ event_type: 'PLAN_CANCELLED', cancelled_reason: reason, supersedes_event_id: old.event_id || null }, old); setMessage('Đã ghi event hủy; không xóa lịch sử.'); history(); render(); } catch (error) { setMessage(`Không hủy được kế hoạch: ${error.message}`, true); } }
async function signal() { const amount = Number(document.getElementById('sa').value) || 0; const date = document.getElementById('sd').value; if (!amount || !date) return setMessage('Nhập đủ số tiền và ngày khách báo thanh toán.', true); try { await appendEvent({ event_type: 'PAYMENT_REPORTED', signal_type: document.getElementById('st').value, amount, expected_date: date, note: document.getElementById('sn').value, payload: {} }); const event = currentEvents[currentEvents.length - 1]; const file = document.getElementById('unc').files[0]; if (online && file && event?.event_id) { const safeName = file.name.replace(/[^a-zA-Z0-9._-]/g, '_'); const path = `${current.project_id}/${current.shop_id}/${event.event_id}/${safeName}`; const { error: uploadError } = await supabaseClient.storage.from(cfg.EVIDENCE_BUCKET || 'unc').upload(path, file, { upsert: false }); if (uploadError) throw uploadError; const { error: metadataError } = await supabaseClient.from('evidence_files').insert({ payment_event_id: event.event_id, project_id: current.project_id, shop_id: current.shop_id, storage_path: path, original_filename: file.name, mime_type: file.type, size_bytes: file.size, uploaded_by: currentUser.id }); if (metadataError) throw metadataError; } setMessage('Đã lưu Payment Signal. Đây không phải tiền SAP đã thu.'); history(); render(); } catch (error) { setMessage(`Không lưu được Payment Signal/UNC: ${error.message}`, true); } }
function history() { const node = document.getElementById('hist'); const events = [...currentEvents].reverse(); node.innerHTML = events.length ? events.map(event => `<div class="event"><b>${esc(event.event_type || event.type)}</b> · ${esc(new Date(event.event_time || event.at).toLocaleString('vi-VN'))}<br>${event.amount != null ? fmt(event.amount) : ''} ${esc(event.expected_date || event.date || '')} ${esc(event.signal_type || '')}<div class="muted">${esc(event.note || event.cancelled_reason || '')}</div></div>`).join('') : '<span class="muted">Chưa có lịch sử.</span>'; }
function init() { document.getElementById('q').addEventListener('input', render); document.querySelectorAll('[data-filter]').forEach(button => button.addEventListener('click', () => { filter = button.dataset.filter; render(); })); if (!online) return; supabaseClient.auth.getSession().then(async ({ data }) => { if (data.session) { currentUser = data.session.user; await enterApp(); } }); supabaseClient.auth.onAuthStateChange(async (_event, session) => { if (session && !currentUser) { currentUser = session.user; await enterApp(); } }); }
window.go = go; window.plan = plan; window.cancelPlan = cancelPlan; window.signal = signal; window.closeShop = () => document.getElementById('shop').close(); window.closeInfo = () => document.getElementById('info').close(); window.addEventListener('DOMContentLoaded', init);
