const cfg = window.STAFF_APP_CONFIG || {};
const accessId = new URLSearchParams(window.location.search).get('staff') || '';
const online = Boolean(window.supabase && cfg.SUPABASE_URL && cfg.SUPABASE_ANON_KEY && !String(cfg.SUPABASE_URL).includes('YOUR_') && !String(cfg.SUPABASE_ANON_KEY).includes('YOUR_'));
const supabaseClient = online ? window.supabase.createClient(cfg.SUPABASE_URL, cfg.SUPABASE_ANON_KEY, {
  auth: { autoRefreshToken: true, persistSession: true, detectSessionInUrl: true, flowType: 'implicit' }
}) : null;
const demoShops = [
  { project_id: 'OCEAN_CITY', shop_id: 'TP.TV-42', cskh_name: 'Nguyễn A', cbld_name: 'CBLĐ Demo', ps_kpi: 120000000, ps_collected: 60000000 },
  { project_id: 'OCEAN_CITY', shop_id: 'HA.01-15', cskh_name: 'Nguyễn A', cbld_name: 'CBLĐ Demo', ps_kpi: 85000000, ps_collected: 70000000 },
  { project_id: 'OCEAN_CITY', shop_id: 'SF.02-08', cskh_name: 'Nguyễn A', cbld_name: 'CBLĐ Demo', ps_kpi: 150000000, ps_collected: 90000000 }
];
let shops = [], current = null, currentEvents = [], filter = 'all', currentUser = null, currentProfile = null;
const fmt = value => new Intl.NumberFormat('vi-VN').format(Number(value) || 0) + ' ₫';
const localDate = () => new Date().toISOString().slice(0, 10);
const eventKey = shop => `staffv1:${shop.project_id}:${shop.shop_id}`;
const localState = shop => JSON.parse(localStorage.getItem(eventKey(shop)) || '{"events":[]}');
const localSave = (shop, state) => localStorage.setItem(eventKey(shop), JSON.stringify(state));
const latestOf = (events, types) => [...events].reverse().find(e => types.includes(e.event_type || e.type));
const esc = value => String(value ?? '').replace(/[&<>"']/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch]));
function setMessage(text, isError = false) { const node = document.getElementById('message'); if (node) { node.textContent = text; node.className = isError ? 'message error' : 'message'; } const loginNode = document.getElementById('loginMessage'); if (loginNode) { loginNode.textContent = text; loginNode.className = isError ? 'message error' : 'message'; } }
function normalizeShop(row) { return { project_id: row.project_id || row.project || cfg.PROJECT_ID || 'OCEAN_CITY', shop_id: row.shop_id || row.shop, cskh_name: row.cskh_name || row.cskh || '', cbld_name: row.cbld_name || row.cbld || '', ps_kpi: Number(row.ps_kpi ?? row.ps ?? 0), ps_collected: Number(row.ps_collected ?? row.col ?? 0), official_kpi: Number(row.official_kpi ?? row.ps_kpi ?? row.ps ?? 0), official_collected: Number(row.official_collected ?? row.ps_collected ?? row.col ?? 0) }; }
async function loadOnlineShops() { const { data: assignments, error: assignmentError } = await supabaseClient.from('assignments').select('project_id,shop_id,cskh_name,cbld_name'); if (assignmentError) throw assignmentError; const { data: debtRows, error: debtError } = await supabaseClient.from('shop_debt_snapshot').select('project_id,shop_id,as_of,ps_kpi,ps_collected,official_kpi,official_collected').order('as_of', { ascending: false }); if (debtError) throw debtError; const latest = new Map(); (debtRows || []).forEach(row => { const key = `${row.project_id}::${row.shop_id}`; if (!latest.has(key)) latest.set(key, row); }); shops = (assignments || []).map(row => normalizeShop({ ...row, ...(latest.get(`${row.project_id}::${row.shop_id}`) || {}) })); }
async function loadProfile(user) { if (!online) return { user_id: user?.id || 'demo', email: user?.email || document.getElementById('email')?.value || 'demo', role: 'CSKH', display_name: 'Demo Staff', staff_access_id: accessId || null, active: true }; const { data, error } = await supabaseClient.from('profiles').select('user_id,email,role,display_name,staff_access_id,active').eq('user_id', user.id).maybeSingle(); if (error) throw error; if (!data || data.active === false) throw new Error('ACCESS_DENIED'); if (accessId && data.staff_access_id !== accessId) throw new Error('ACCESS_DENIED'); return data; }
function renderAccount() { const node = document.getElementById('account'); if (!node || !currentProfile) return; node.innerHTML = `<b>${esc(currentProfile.display_name || currentProfile.email || 'Staff')}</b><span>${esc(currentProfile.role || '')} · ${esc(currentProfile.email || '')}</span>${accessId ? `<small>Staff Access: ${esc(accessId)}</small>` : ''}`; const adminButton = document.getElementById('adminAccessButton'); if (adminButton) adminButton.hidden = currentProfile.role !== 'ADMIN'; }
async function enterApp(user) { try { currentProfile = await loadProfile(user); currentUser = user; document.getElementById('login').hidden = true; document.getElementById('app').hidden = false; renderAccount(); setMessage(online ? 'Đã kết nối Pilot Supabase. Dữ liệu công nợ chỉ đọc.' : 'Bản Candidate offline: dữ liệu demo lưu trên thiết bị.'); if (online) await loadOnlineShops(); else shops = demoShops.map(normalizeShop); render(); } catch (error) { currentUser = null; currentProfile = null; if (online) await supabaseClient.auth.signOut({ scope: 'local' }).catch(() => {}); document.getElementById('login').hidden = false; document.getElementById('app').hidden = true; setMessage('Không có quyền truy cập Staff Link này.', true); } }
function currentPlan(events) { const plan = latestOf(events, ['PLAN_CHANGED', 'PLAN_CREATED']); const cancelled = latestOf(events, ['PLAN_CANCELLED']); return plan && (!cancelled || new Date(cancelled.event_time || cancelled.at) < new Date(plan.event_time || plan.at)) ? plan : null; }
function shopEvents(shop) { return online ? (shop.__events || []) : (localState(shop).events || []); }
function matchesFilter(shop) { const debt = Math.max(0, shop.ps_kpi - shop.ps_collected); const events = shopEvents(shop); const plan = currentPlan(events); const signalEvent = latestOf(events, ['PAYMENT_REPORTED']); const date = plan?.expected_date || plan?.date || ''; if (filter === 'noplan') return !plan; if (filter === 'signal') return Boolean(signalEvent); if (filter === 'debt') return debt > 0; if (filter === 'today') return date === localDate(); if (filter === 'overdue') return Boolean(date && date < localDate()); return true; }
function render() { const list = document.getElementById('list'); if (!list) return; const query = (document.getElementById('q').value || '').toLowerCase(); list.innerHTML = ''; shops.filter(shop => shop.shop_id.toLowerCase().includes(query) && matchesFilter(shop)).forEach(shop => { const events = shopEvents(shop); const plan = currentPlan(events); const signalEvent = latestOf(events, ['PAYMENT_REPORTED']); const debt = Math.max(0, shop.ps_kpi - shop.ps_collected); const card = document.createElement('div'); card.className = 'card'; card.innerHTML = `<b>${esc(shop.shop_id)}</b><div class="muted">${esc(shop.cskh_name)} · ${esc(shop.cbld_name)}</div><p>Còn phải thu: <b>${fmt(debt)}</b></p><span class="badge">${plan ? 'Có kế hoạch' : 'Chưa có kế hoạch'}</span>${signalEvent ? '<span class="badge">Có tín hiệu</span>' : ''}<button type="button">Mở Shop</button>`; card.querySelector('button').addEventListener('click', () => openShop(shop.shop_id)); list.appendChild(card); }); }
async function eventsFor(shop) { if (!online) return localState(shop).events || []; const { data, error } = await supabaseClient.from('staff_events').select('*').eq('project_id', shop.project_id).eq('shop_id', shop.shop_id).order('event_time', { ascending: true }); if (error) throw error; return data || []; }
async function openShop(id) { current = shops.find(shop => shop.shop_id === id); if (!current) return; try { currentEvents = await eventsFor(current); } catch (error) { return setMessage(`Không đọc được lịch sử: ${error.message}`, true); } const plan = currentPlan(currentEvents); document.getElementById('title').textContent = current.shop_id; document.getElementById('debt').innerHTML = `Nợ PS: <b>${fmt(current.ps_kpi)}</b><br>Đã thu PS: <b>${fmt(current.ps_collected)}</b><br>Còn phải thu: <b>${fmt(current.ps_kpi - current.ps_collected)}</b>`; document.getElementById('pa').value = plan?.amount || ''; document.getElementById('pd').value = plan?.expected_date || plan?.date || ''; document.getElementById('pn').value = plan?.note || ''; history(); document.getElementById('shop').showModal(); }
async function appendEvent(payload, previous = null) { if (!online) { const state = localState(current); state.events.push({ ...payload, type: payload.event_type, id: crypto.randomUUID(), at: new Date().toISOString(), by: document.getElementById('email').value || 'demo', before: previous || null }); localSave(current, state); currentEvents = state.events; return; } const row = { ...payload, project_id: current.project_id, shop_id: current.shop_id, created_by: currentUser.id }; const { data, error } = await supabaseClient.from('staff_events').insert(row).select().single(); if (error) throw error; currentEvents.push(data); }
async function plan() { const amount = Number(document.getElementById('pa').value) || 0; const expectedDate = document.getElementById('pd').value; if (!amount || !expectedDate) return setMessage('Nhập đủ số tiền và ngày dự kiến thu.', true); const old = currentPlan(currentEvents); try { await appendEvent({ event_type: old ? 'PLAN_CHANGED' : 'PLAN_CREATED', amount, expected_date: expectedDate, note: document.getElementById('pn').value, supersedes_event_id: old?.event_id || null }, old); setMessage('Đã lưu kế hoạch bằng event mới; lịch sử cũ vẫn được giữ.'); history(); render(); } catch (error) { setMessage(`Không lưu được kế hoạch: ${error.message}`, true); } }
async function cancelPlan() { const old = currentPlan(currentEvents); if (!old) return setMessage('Shop chưa có kế hoạch hiện tại.', true); const reason = window.prompt('Lý do hủy kế hoạch?'); if (!reason) return; try { await appendEvent({ event_type: 'PLAN_CANCELLED', cancelled_reason: reason, supersedes_event_id: old.event_id || null }, old); setMessage('Đã ghi event hủy; không xóa lịch sử.'); history(); render(); } catch (error) { setMessage(`Không hủy được kế hoạch: ${error.message}`, true); } }
async function signal() { const amount = Number(document.getElementById('sa').value) || 0; const date = document.getElementById('sd').value; if (!amount || !date) return setMessage('Nhập đủ số tiền và ngày khách báo thanh toán.', true); try { await appendEvent({ event_type: 'PAYMENT_REPORTED', signal_type: document.getElementById('st').value, amount, expected_date: date, note: document.getElementById('sn').value, payload: {} }); const event = currentEvents[currentEvents.length - 1]; const file = document.getElementById('unc').files[0]; if (online && file && event?.event_id) { const safeName = file.name.replace(/[^a-zA-Z0-9._-]/g, '_'); const path = `${current.project_id}/${current.shop_id}/${event.event_id}/${safeName}`; const { error: uploadError } = await supabaseClient.storage.from(cfg.EVIDENCE_BUCKET || 'unc').upload(path, file, { upsert: false }); if (uploadError) throw uploadError; const { error: metadataError } = await supabaseClient.from('evidence_files').insert({ payment_event_id: event.event_id, project_id: current.project_id, shop_id: current.shop_id, storage_path: path, original_filename: file.name, mime_type: file.type, size_bytes: file.size, uploaded_by: currentUser.id }); if (metadataError) throw metadataError; } setMessage('Đã lưu Payment Signal. Đây không phải tiền SAP đã thu.'); history(); render(); } catch (error) { setMessage(`Không lưu được Payment Signal/UNC: ${error.message}`, true); } }
function history() { const node = document.getElementById('hist'); const events = [...currentEvents].reverse(); node.innerHTML = events.length ? events.map(event => `<div class="event"><b>${esc(event.event_type || event.type)}</b> · ${esc(new Date(event.event_time || event.at).toLocaleString('vi-VN'))}<br>${event.amount != null ? fmt(event.amount) : ''} ${esc(event.expected_date || event.date || '')} ${esc(event.signal_type || '')}<div class="muted">${esc(event.note || event.cancelled_reason || '')}</div></div>`).join('') : '<span class="muted">Chưa có lịch sử.</span>'; }
async function logout() { if (online) await supabaseClient.auth.signOut({ scope: 'local' }); currentUser = null; currentProfile = null; shops = []; document.getElementById('app').hidden = true; document.getElementById('login').hidden = false; setMessage('Đã đăng xuất.'); }
async function loadAdminAccessList() { if (!online || currentProfile?.role !== 'ADMIN') return; const [{ data: profiles, error: pe }, { data: assignments, error: ae }] = await Promise.all([supabaseClient.from('profiles').select('user_id,email,role,display_name,staff_access_id,active'), supabaseClient.from('assignments').select('cskh_user_id,cbld_user_id')]); if (pe || ae) throw pe || ae; const counts = {}; (assignments || []).forEach(a => { [a.cskh_user_id, a.cbld_user_id].filter(Boolean).forEach(id => { counts[id] = (counts[id] || 0) + 1; }); }); document.getElementById('adminList').innerHTML = (profiles || []).map(p => `<tr><td>${esc(p.display_name || '')}</td><td>${esc(p.role)}</td><td>${esc(p.email)}</td><td>${esc(p.staff_access_id || 'Chưa cấp')}</td><td>${counts[p.user_id] || 0}</td><td>${p.active ? 'Đang hoạt động' : 'Tạm khóa'}</td></tr>`).join('') || '<tr><td colspan="6">Chưa có nhân sự Pilot.</td></tr>'; document.getElementById('adminDialog').showModal(); }
function init() { document.getElementById('q').addEventListener('input', render); document.querySelectorAll('[data-filter]').forEach(button => button.addEventListener('click', () => { filter = button.dataset.filter; render(); })); if (!online) return; supabaseClient.auth.getSession().then(async ({ data }) => { if (data.session) await enterApp(data.session.user); }); supabaseClient.auth.onAuthStateChange(async (_event, session) => { if (session) await enterApp(session.user); }); }
async function go() { const email = document.getElementById('email').value.trim(); if (!email) return setMessage('Nhập email công việc để nhận liên kết đăng nhập.', true); if (!online) return enterApp(); const redirect = `${window.location.origin}${window.location.pathname}${accessId ? `?staff=${encodeURIComponent(accessId)}` : ''}`; const { error } = await supabaseClient.auth.signInWithOtp({ email, options: { emailRedirectTo: redirect } }); if (error) return setMessage(`Không gửi được liên kết đăng nhập: ${error.message}`, true); setMessage('Đã gửi liên kết đăng nhập. Kiểm tra email công việc rồi mở liên kết trong cùng trình duyệt.'); }
window.go = go; window.plan = plan; window.cancelPlan = cancelPlan; window.signal = signal; window.logout = logout; window.loadAdminAccessList = loadAdminAccessList; window.closeShop = () => document.getElementById('shop').close(); window.closeInfo = () => document.getElementById('info').close(); window.closeAdmin = () => document.getElementById('adminDialog').close(); window.addEventListener('DOMContentLoaded', init);
